services:
  web:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    container_name: my_web_fixed
    ports:
      - "80:80"
      - "9000:9000"
    restart: always
    working_dir: /www
    user: "1000:1000"  # 使用非root用户
    volumes:
      - /home/app/default:/www/
      - ./conf/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./supervisor/supervisor.d:/etc/supervisor/conf.d
      - ./log:/var/log
    environment:
      - TZ=Asia/Shanghai
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: false
    tmpfs:
      - /tmp
      - /var/tmp

networks:
  default:
    driver: bridge
